backend:
  name: git-gateway
  branch: master

media_folder: "assets/img"
public_folder: "/img"

site_url: https://scumboy.co.za
display_url: https://scumboy.co.za
logo_url: https://scumboy.co.za/

collections:

  # Page Content
  - name: 'pages'
    label: 'Pages'
    folder: 'content/pages'
    format: 'frontmatter'
    create: true
    slug: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Shop Description', name: 'body', widget: 'markdown' }
      - { label: 'Banner Title', name: 'bannerTitle', widget: 'string' }
      - { label: 'Banner Subtitle', name: 'bannerSubtitle', widget: 'string' }
      - { label: 'Banner Button Text', name: 'bannerButtonText', widget: 'string' }
      - { label: 'Banner Product Slug', name: 'bannerLink', widget: 'string' }
      - { label: 'Banner Background Image', name: 'bannerImage', widget: 'string' }

  # Data
  - name: 'press'
    label: 'Press'
    files:
      - label: 'Press Item'
        name: 'press'
        file: 'content/press/press'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Blog Name', name: 'blogName', widget: 'string' }
          - { label: 'Link', name: 'link', widget: 'string' }
          - { label: 'Year', name: 'year', widget: 'datetime' }

